# Generated by Django 5.1.5 on 2025-03-07 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0004_logger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logger',
            name='name',
        ),
        migrations.AddField(
            model_name='logger',
            name='favorite_dish',
            field=models.CharField(choices=[('italian', 'Italian'), ('greek', 'Greek'), ('turkish', 'Turkish')], default='italian', max_length=50),
        ),
        migrations.AddField(
            model_name='logger',
            name='first_name',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='logger',
            name='last_name',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='logger',
            name='reservation_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='logger',
            name='email',
            field=models.EmailField(default='noemail@example.com', max_length=200),
        ),
    ]
