# Generated by Django 5.1.5 on 2025-03-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0005_remove_logger_name_logger_favorite_dish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='logger',
            name='favorite_dish',
            field=models.CharField(choices=[('italian', 'Italian'), ('greek', 'Greek'), ('turkish', 'Turkish')], max_length=50),
        ),
        migrations.AlterField(
            model_name='logger',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='logger',
            name='last_name',
            field=models.CharField(max_length=200),
        ),
    ]
